### PR TITLE
working cog predict, updated readme

### PR DESCRIPTION
**Pull request by daanelson**
Hey! Added a `cog.yaml` and `predict.py` file so that we have the code that powers the riffusion demo on Replicate (https://replicate.com/hmartiro/riffusion) colocated with the riffusion source inference code.

### CODE REVIEW

**Comment by daanelson** [comment]
good q @hmartiro. `predict.py` can live in a subdirectory, but `cog.yaml` has to be in the project root. I went ahead and moved `predict.py` into the `riffusion` module & renamed it `cog_riffusion.py`, let me know if that works or if you have something else in mind.

**Comment by rhelsing** [comment]
@daanelson is it possible to allow for custom seed image input to the cog? Or some of the other options that are available on the inference server like a negative prompt?

**Comment by hmartiro** [comment]
@daanelson sorry for the delay. With the v0.3.0 release (https://github.com/riffusion/riffusion/releases/tag/v0.3.0) this should simplify the code and integration

**Comment by hmartiro** [comment]
@daanelson since I didn't know how to push to your branch / this PR, I duplicated and updated it at #57. I'll tag you there for a question

**Pull request closed without merging**
