### PR TITLE
Audio to audio

### PR DESCRIPTION
**Pull request by hmartiro**
Topic: audio_to_audio
Relative: audio_splitter

### CODE REVIEW

**Comment by hmartiro** [comment]
Reviews in this chain:
└https://github.com/riffusion/riffusion/pull/62 Audio splitter
　└**https://github.com/riffusion/riffusion/pull/63** **Audio to audio**

**Comment by hmartiro** [comment]
| # | head | base | diff | date | summary |
| - | - | - | - | - | - |
| 0 | [f1f0d9e7](/riffusion/riffusion/commit/f1f0d9e74cd001c46951147665502a69bec5220a) | [94d5fb2b](/riffusion/riffusion/commit/94d5fb2b708a3deb5c89d27219d27243e2784139) | [diff](/riffusion/riffusion/compare/94d5fb2b708a3deb5c89d27219d27243e2784139..f1f0d9e74cd001c46951147665502a69bec5220a) | Jan 5 4:54 AM |  4 files changed, 341 insertions(+), 5 deletions(-) |

**Review by SethForsgren — APPROVED** [review]
working now!

**Comment by hmartiro** [comment]
* why are the lengths messed up? possibly resizing image and speed
* incorporate splitting out vocals as an optional step

**Pull request merged**
